spring:
  application:
    name: BE

  profiles:
    active: local

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-secret: ${KAKAO_REST_API_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL} # jdbc:mysql://localhost:3306/{데이터베이스명}
    username: ${DB_USER} # MySQL 유저 이름
    password: ${DB_PW} # MySQL 비밀번호

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  neo4j:
    uri: ${NEO_URL}
    authentication:
      username: ${NEO_USERNAME}
      password: ${NEO_PW}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: stology-s3
        path: dev/

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}
    # 랜덤 문자열 뽑는 명령어(cmd) : powershell -Command "-join ((65..90)+(97..122)+(48..57) | Get-Random -Count 64 | % {[char]$_})"
    expiration:
      access: ${JWT_ACCESS_EXPIRATION:3600000}
      refresh: ${JWT_REFRESH_EXPIRATION:604800000}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
